-- =====================================================================
-- Employee Management System - Database schema for MySQL 8+
-- =====================================================================
-- Differences from the default schema.sql (H2):
--   * BIGINT AUTO_INCREMENT instead of GENERATED BY DEFAULT AS IDENTITY
--   * CREATE INDEX without IF NOT EXISTS (not supported by MySQL)
--   * MySQL has no DROP CONSTRAINT IF EXISTS, so re-running this script
--     against an existing database fails at the ALTER TABLE step — the
--     MySQL profile targets a fresh database (create it, run once).
-- Same tables, same columns, same constraints.

CREATE TABLE IF NOT EXISTS department (
    id                 BIGINT AUTO_INCREMENT PRIMARY KEY,
    name               VARCHAR(100) NOT NULL UNIQUE,
    creation_date      DATE         NOT NULL,
    department_head_id BIGINT       NULL
);

CREATE TABLE IF NOT EXISTS employee (
    id                       BIGINT AUTO_INCREMENT PRIMARY KEY,
    name                     VARCHAR(120)  NOT NULL,
    date_of_birth            DATE          NOT NULL,
    salary                   DECIMAL(12,2) NOT NULL,
    department_id            BIGINT        NOT NULL,
    address                  VARCHAR(255)  NOT NULL,
    role_title               VARCHAR(100)  NOT NULL,
    joining_date             DATE          NOT NULL,
    yearly_bonus_percentage  DECIMAL(5,2)  NOT NULL,
    reporting_manager_id     BIGINT        NULL,

    CONSTRAINT fk_employee_department
        FOREIGN KEY (department_id) REFERENCES department (id),
    CONSTRAINT fk_employee_reporting_manager
        FOREIGN KEY (reporting_manager_id) REFERENCES employee (id)
) ENGINE = InnoDB;

-- Added after the employee table exists because department.department_head_id
-- and employee.department_id reference each other (cyclic dependency).
ALTER TABLE department
    ADD CONSTRAINT fk_department_head
    FOREIGN KEY (department_head_id) REFERENCES employee (id);

CREATE INDEX idx_employee_department ON employee (department_id);
CREATE INDEX idx_employee_reporting_manager ON employee (reporting_manager_id);
CREATE INDEX idx_department_head ON department (department_head_id);
