-- =====================================================================
-- Employee Management System - Database schema (H2 / MySQL compatible)
-- =====================================================================
-- This script is executed automatically by Spring Boot on startup
-- (spring.sql.init.mode=always) and doubles as the deliverable "DB script
-- to create tables". The statements use standard SQL so the same script
-- works against MySQL/PostgreSQL with minor type tweaks (e.g. DECIMAL).

CREATE TABLE IF NOT EXISTS department (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name               VARCHAR(100) NOT NULL UNIQUE,
    creation_date      DATE         NOT NULL,
    department_head_id BIGINT       NULL
);

CREATE TABLE IF NOT EXISTS employee (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                     VARCHAR(120)  NOT NULL,
    date_of_birth            DATE          NOT NULL,
    salary                   DECIMAL(12,2) NOT NULL,
    department_id            BIGINT        NOT NULL,
    address                  VARCHAR(255)  NOT NULL,
    role_title               VARCHAR(100)  NOT NULL,
    joining_date             DATE          NOT NULL,
    yearly_bonus_percentage  DECIMAL(5,2)  NOT NULL,
    reporting_manager_id     BIGINT        NULL,

    CONSTRAINT fk_employee_department
        FOREIGN KEY (department_id) REFERENCES department (id),
    CONSTRAINT fk_employee_reporting_manager
        FOREIGN KEY (reporting_manager_id) REFERENCES employee (id)
);

-- The department head foreign key is added after the employee table exists
-- because department.department_head_id and employee.department_id reference
-- each other (cyclic dependency).
ALTER TABLE department
    ADD CONSTRAINT fk_department_head
    FOREIGN KEY (department_head_id) REFERENCES employee (id);

-- Indexes supporting the most frequent access paths
CREATE INDEX IF NOT EXISTS idx_employee_department ON employee (department_id);
CREATE INDEX IF NOT EXISTS idx_employee_reporting_manager ON employee (reporting_manager_id);
CREATE INDEX IF NOT EXISTS idx_department_head ON department (department_head_id);
